version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    depends_on:
      - step-ca

  step-ca:
    image: smallstep/step-ca
    ports:
      - "9000:9000"
    volumes:
      - ./data/ca:/home/step